<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._VQq6sL' shared service.

return $this->privates['.service_locator._VQq6sL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cart' => ['privates', 'App\\Services\\ShoppingCart', 'getShoppingCartService.php', true],
    'product' => ['privates', '.errored..service_locator._VQq6sL.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator._VQq6sL": it references class "App\\Entity\\Product" but no such service exists.'],
], [
    'cart' => 'App\\Services\\ShoppingCart',
    'product' => 'App\\Entity\\Product',
]);
