<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MPYtGQ1' shared service.

return $this->privates['.service_locator.MPYtGQ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.wyrb61.', 'get_ServiceLocator_Wyrb61_Service.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\ShoppingCartController::addToCart' => ['privates', '.service_locator._VQq6sL', 'get_ServiceLocator_VQq6sLService.php', true],
    'App\\Controller\\ShoppingCartController::cart' => ['privates', '.service_locator.RadNmSQ', 'get_ServiceLocator_RadNmSQService.php', true],
    'App\\Controller\\ShoppingCartController::checkout' => ['privates', '.service_locator.RadNmSQ', 'get_ServiceLocator_RadNmSQService.php', true],
    'App\\Controller\\ShoppingCartController::removeFromCart' => ['privates', '.service_locator.sYb7zrE', 'get_ServiceLocator_SYb7zrEService.php', true],
    'App\\Controller\\ShoppingCartController::updateQuantities' => ['privates', '.service_locator.sYb7zrE', 'get_ServiceLocator_SYb7zrEService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.wyrb61.', 'get_ServiceLocator_Wyrb61_Service.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\ShoppingCartController:addToCart' => ['privates', '.service_locator._VQq6sL', 'get_ServiceLocator_VQq6sLService.php', true],
    'App\\Controller\\ShoppingCartController:cart' => ['privates', '.service_locator.RadNmSQ', 'get_ServiceLocator_RadNmSQService.php', true],
    'App\\Controller\\ShoppingCartController:checkout' => ['privates', '.service_locator.RadNmSQ', 'get_ServiceLocator_RadNmSQService.php', true],
    'App\\Controller\\ShoppingCartController:removeFromCart' => ['privates', '.service_locator.sYb7zrE', 'get_ServiceLocator_SYb7zrEService.php', true],
    'App\\Controller\\ShoppingCartController:updateQuantities' => ['privates', '.service_locator.sYb7zrE', 'get_ServiceLocator_SYb7zrEService.php', true],
], [
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\ShoppingCartController::addToCart' => '?',
    'App\\Controller\\ShoppingCartController::cart' => '?',
    'App\\Controller\\ShoppingCartController::checkout' => '?',
    'App\\Controller\\ShoppingCartController::removeFromCart' => '?',
    'App\\Controller\\ShoppingCartController::updateQuantities' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\ShoppingCartController:addToCart' => '?',
    'App\\Controller\\ShoppingCartController:cart' => '?',
    'App\\Controller\\ShoppingCartController:checkout' => '?',
    'App\\Controller\\ShoppingCartController:removeFromCart' => '?',
    'App\\Controller\\ShoppingCartController:updateQuantities' => '?',
]);
